// Note, most of this file was generated by AI
export type RGBObject = { r: number; g: number; b: number };
export type RGBArray = [number, number, number];
export type ColorValue = string | number | RGBObject | RGBArray;

export type NormalizedRGB = { r: number; g: number; b: number };

type ColorKind = 'string' | 'number' | 'object' | 'array';

export interface ParsedColor {
  normalized: NormalizedRGB;
  kind: ColorKind;
  max: number;
}

function clamp01(v: number) {
  return Math.min(1, Math.max(0, v));
}

function isFiniteRGB(c: NormalizedRGB) {
  return Number.isFinite(c.r) && Number.isFinite(c.g) && Number.isFinite(c.b);
}

function componentToHex(v: number) {
  const hex = Math.round(clamp01(v) * 255)
    .toString(16)
    .padStart(2, '0');
  return hex;
}

export function normalizedToHex(c: NormalizedRGB): string {
  return '#' + componentToHex(c.r) + componentToHex(c.g) + componentToHex(c.b);
}

function hexToNormalized(hex: string): NormalizedRGB | null {
  hex = hex.trim().replace('#', '');

  // strict hex validation
  if (!/^([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(hex)) {
    return null;
  }

  if (hex.length === 3) {
    hex = hex
      .split('')
      .map((c) => c + c)
      .join('');
  }

  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;

  return { r, g, b };
}

function numberToNormalized(num: number): NormalizedRGB | null {
  if (!Number.isFinite(num)) return null;

  const r = ((num >> 16) & 255) / 255;
  const g = ((num >> 8) & 255) / 255;
  const b = (num & 255) / 255;

  return { r, g, b };
}

function rgbStringToNormalized(str: string): NormalizedRGB | null {
  const match = str.match(/\d+(\.\d+)?/g);
  if (!match || match.length < 3) return null;

  const [r, g, b] = match.map(Number);

  if ([r, g, b].some((v) => !Number.isFinite(v))) return null;

  return {
    r: clamp01(r > 1 ? r / 255 : r),
    g: clamp01(g > 1 ? g / 255 : g),
    b: clamp01(b > 1 ? b / 255 : b),
  };
}

export function parseColor(
  value: ColorValue,
  explicitMax?: number
): ParsedColor | null {
  // ---- string ----
  if (typeof value === 'string') {
    const normalized = value.startsWith('#')
      ? hexToNormalized(value)
      : rgbStringToNormalized(value);

    if (!normalized || !isFiniteRGB(normalized)) return null;

    return {
      normalized,
      kind: 'string',
      max: 255,
    };
  }

  // ---- number ----
  if (typeof value === 'number') {
    const normalized = numberToNormalized(value);
    if (!normalized) return null;

    return {
      normalized,
      kind: 'number',
      max: 255,
    };
  }

  // ---- array ----
  if (Array.isArray(value)) {
    if (value.length < 3) return null;

    const max = explicitMax ?? (value.some((v) => v > 1) ? 255 : 1);

    const normalized = {
      r: value[0] / max,
      g: value[1] / max,
      b: value[2] / max,
    };

    if (!isFiniteRGB(normalized)) return null;

    return {
      normalized,
      kind: 'array',
      max,
    };
  }

  // ---- object ----
  const max =
    explicitMax ?? (Object.values(value).some((v) => v > 1) ? 255 : 1);

  const normalized = {
    r: value.r / max,
    g: value.g / max,
    b: value.b / max,
  };

  if (!isFiniteRGB(normalized)) return null;

  return {
    normalized,
    kind: 'object',
    max,
  };
}

export function applyColor(
  target: ColorValue,
  normalized: NormalizedRGB,
  kind: ParsedColor['kind'],
  max: number
): ColorValue {
  const scaled = {
    r: clamp01(normalized.r) * max,
    g: normalized.g * max,
    b: normalized.b * max,
  };

  switch (kind) {
    case 'string':
      return normalizedToHex(normalized);

    case 'number':
      return (
        ((Math.round(scaled.r) & 255) << 16) |
        ((Math.round(scaled.g) & 255) << 8) |
        (Math.round(scaled.b) & 255)
      );

    case 'array':
      (target as RGBArray)[0] = scaled.r;
      (target as RGBArray)[1] = scaled.g;
      (target as RGBArray)[2] = scaled.b;
      return target;

    case 'object':
      (target as RGBObject).r = scaled.r;
      (target as RGBObject).g = scaled.g;
      (target as RGBObject).b = scaled.b;
      return target;
  }
}
