// Note, most of this file was generated by AI
import type { ColorValue } from '../core/types';

export type RGBA = { r: number; g: number; b: number; a: number };
export type ColorFormatInfo = {
  kind: 'string' | 'object' | 'array';
  type: 'rgb' | 'hsl';
  max: number; // 1 or 255
};
export interface ParsedColor {
  rgba: RGBA;
  info: ColorFormatInfo;
}

const HEX_RE = /^#([a-f\d]{3,8})$/i;

/** Helper to convert 0-1 component to 2-digit hex */
const toHexStr = (v: number) =>
  Math.round(v * 255)
    .toString(16)
    .padStart(2, '0');

export function isColor(v: unknown): v is ColorValue {
  if (typeof v === 'string') {
    const s = v.trim();
    return HEX_RE.test(s) || s.startsWith('rgb') || s.startsWith('hsl');
  }
  if (Array.isArray(v)) {
    return (
      (v.length === 3 || v.length === 4) &&
      v.every((n) => typeof n === 'number' && Number.isFinite(n))
    );
  }
  if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
    const obj = v as Record<string, unknown>;
    if ('$' in obj || 'value' in obj) return false;
    const hasRgb = ['r', 'g', 'b'].every((k) => typeof obj[k] === 'number');
    const hasHsl = ['h', 's', 'l'].every((k) => typeof obj[k] === 'number');
    return hasRgb || hasHsl;
  }
  return false;
}

export function parseColor(v: unknown): ParsedColor | null {
  if (typeof v === 'string') {
    const s = v.trim();
    const hex = HEX_RE.exec(s);
    if (hex) {
      const val = hex[1];
      const isShort = val.length <= 4;
      const step = isShort ? 1 : 2;
      const parse = (start: number) => {
        const chunk = val.slice(start, start + step);
        return Number.parseInt(isShort ? chunk + chunk : chunk, 16) / 255;
      };
      return {
        rgba: {
          r: parse(0),
          g: parse(step),
          b: parse(step * 2),
          a: val.length === (isShort ? 4 : 8) ? parse(step * 3) : 1,
        },
        info: { kind: 'string', type: 'rgb', max: 255 },
      };
    }
    // Basic fallback for css strings rgb/hsl
    const isRgb = s.startsWith('rgb');
    const isHsl = s.startsWith('hsl');
    if (!isRgb && !isHsl) return null;

    const match = s.match(/\d+(\.\d+)?/g);
    if (!match || match.length < 3) return null;

    const nums = match.map(Number);
    if (isHsl)
      return {
        rgba: hslToRgb(
          nums[0] / 360,
          nums[1] / 100,
          nums[2] / 100,
          nums[3] ?? 1
        ),
        info: { kind: 'string', type: 'hsl', max: 1 },
      };

    return {
      rgba: {
        r: nums[0] / 255,
        g: nums[1] / 255,
        b: nums[2] / 255,
        a: nums[3] ?? 1,
      },
      info: { kind: 'string', type: 'rgb', max: 255 },
    };
  }

  if (Array.isArray(v)) {
    const arr = v as unknown[];
    if (
      arr.length < 3 ||
      typeof arr[0] !== 'number' ||
      typeof arr[1] !== 'number' ||
      typeof arr[2] !== 'number'
    )
      return null;
    const r = arr[0],
      g = arr[1],
      b = arr[2];
    const a = typeof arr[3] === 'number' ? arr[3] : 1;
    const max = r > 1 || g > 1 || b > 1 ? 255 : 1;
    return {
      rgba: { r: r / max, g: g / max, b: b / max, a },
      info: { kind: 'array', type: 'rgb', max },
    };
  }

  if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
    const obj = v as Record<string, unknown>;
    if (
      'r' in obj &&
      'g' in obj &&
      'b' in obj &&
      typeof obj.r === 'number' &&
      typeof obj.g === 'number' &&
      typeof obj.b === 'number'
    ) {
      const r = obj.r,
        g = obj.g,
        b = obj.b;
      const a = typeof obj.a === 'number' ? obj.a : 1;
      const max = r > 1 || g > 1 || b > 1 ? 255 : 1;
      return {
        rgba: { r: r / max, g: g / max, b: b / max, a },
        info: { kind: 'object', type: 'rgb', max },
      };
    }
    if (
      'h' in obj &&
      's' in obj &&
      'l' in obj &&
      typeof obj.h === 'number' &&
      typeof obj.s === 'number' &&
      typeof obj.l === 'number'
    ) {
      const h = obj.h,
        s = obj.s,
        l = obj.l;
      const a = typeof obj.a === 'number' ? obj.a : 1;
      const max = h > 1 || s > 1 || l > 1 ? 255 : 1;
      return {
        rgba: hslToRgb(h / (max === 255 ? 360 : 1), s / max, l / max, a),
        info: { kind: 'object', type: 'hsl', max },
      };
    }
  }
  return null;
}

export function formatColor(rgba: RGBA, info: ColorFormatInfo): ColorValue {
  const { r, g, b, a } = rgba;
  if (info.kind === 'string') return normalizedToHex(rgba);
  if (info.kind === 'array') {
    const res = [r * info.max, g * info.max, b * info.max];
    if (a < 1) res.push(a);
    return res;
  }
  if (info.type === 'hsl') {
    const { h, s, l } = rgbToHsl(r, g, b);
    const hScaled = h * (info.max === 255 ? 360 : 1);
    const res: { h: number; s: number; l: number; a?: number } = {
      h: hScaled,
      s: s * info.max,
      l: l * info.max,
    };
    if (a < 1) res.a = a;
    return res;
  }
  const res: { r: number; g: number; b: number; a?: number } = {
    r: r * info.max,
    g: g * info.max,
    b: b * info.max,
  };
  if (a < 1) res.a = a;
  return res;
}

export function normalizedToHex({ r, g, b, a }: RGBA): string {
  const alpha = a < 1 ? toHexStr(a) : '';
  return `#${toHexStr(r)}${toHexStr(g)}${toHexStr(b)}${alpha}`;
}

export function normalizedToHex6({ r, g, b }: RGBA): string {
  return `#${toHexStr(r)}${toHexStr(g)}${toHexStr(b)}`;
}

function rgbToHsl(r: number, g: number, b: number) {
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0,
    s;
  if (max === min) h = s = 0;
  else {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
        break;
    }
    h /= 6;
  }
  return { h, s, l };
}

function hslToRgb(h: number, s: number, l: number, a: number): RGBA {
  let r, g, b;
  if (s === 0) r = g = b = l;
  else {
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    const hue2rgb = (t: number) => {
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };
    r = hue2rgb(h + 1 / 3);
    g = hue2rgb(h);
    b = hue2rgb(h - 1 / 3);
  }
  return { r, g, b, a };
}
